name: Pull Request check
on:
  - pull_request
  - workflow_dispatch
env:
  RACK_ENV: test
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    env:
      SIMPLECOV: json
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3', '3.4', '4.0' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: |
          gem install bundler
          bundle install --with development test
      - name: Runs tests
        run: |
          bundle exec rspec -f j -o rspec_results.json -f p
      - name: RSpec Report
        if: always()
        uses: SonicGarden/rspec-report-action@v6
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: rspec_results.json
